<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_US 1</name>
   <tag></tag>
   <elementGuidId>e1af67da-ea76-472e-8235-69586e8a60c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='cvf_phone_cc_aui']/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.a-button-text.a-declarative</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a1f89dc1-30d4-4c31-a28c-d2026f65d6b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-text a-declarative</value>
      <webElementGuid>6200e171-1e77-4209-9621-7e411b3b8799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-func-deps</name>
      <type>Main</type>
      <value>aui-da-a-dropdown-button</value>
      <webElementGuid>9063d98a-54d5-4442-acb8-f1f52b515407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>widget</value>
      <webElementGuid>9999f8b2-1c14-40aa-9c57-9f1375bf478e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-interaction-events</name>
      <type>Main</type>
      <value>click</value>
      <webElementGuid>3ee14ca1-95c7-4896-9c8c-64abae392bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>a-dropdown-button</value>
      <webElementGuid>ad5bf146-2814-476e-8d37-14693541ee46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5bc7b743-bc31-4f32-af9a-1f3c39f85943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>        US +1
</value>
      <webElementGuid>25030936-bdb1-4e13-bc3e-8d3f46b349a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cvf_phone_cc_aui&quot;)/span[@class=&quot;a-button-inner&quot;]/span[@class=&quot;a-button-text a-declarative&quot;]</value>
      <webElementGuid>085c59ae-9064-401f-8441-0748aa330119</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cvf_phone_cc_aui']/span/span</value>
      <webElementGuid>fbf6c790-a30f-4db1-9551-7bae0522dc16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>78ccc812-f719-4c32-9690-78d809e5d300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '        US +1
' or . = '        US +1
')]</value>
      <webElementGuid>b07ed291-9994-480c-92a1-7d5453067fb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
