<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_submit.addToCart</name>
   <tag></tag>
   <elementGuidId>146a55ed-85b6-4c65-91de-14a11e2d5e99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='submit.addToCart']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;submit.addToCart&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9659ba0d-11d5-4bdd-918b-dad27b551874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>97afe22e-4953-4744-8402-180b343e8956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.addToCart</value>
      <webElementGuid>13189d59-3ce0-4019-81d1-5e77420ff84e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-asins</name>
      <type>Main</type>
      <value>[&quot;B0CL9G2GBD&quot;,&quot;B005EJH6Z4&quot;]</value>
      <webElementGuid>f34c4e88-70a5-4361-8b13-d0c0f6c855ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mix-operations</name>
      <type>Main</type>
      <value>AddToCart</value>
      <webElementGuid>93cf7867-40b7-4b36-9cca-ad36ea60ee80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-numitems</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>8f82e054-dbb9-443f-9204-7cb9047d9be6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reftag</name>
      <type>Main</type>
      <value>pd_day0fbt_hardlines_crt</value>
      <webElementGuid>a8a73e16-af7d-4201-bc1a-43d478fa7564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>/cart/add-to-cart/ref=pd_day0fbt_hardlines_crt?_encoding=UTF8&amp;pd_rd_w=KVqnU&amp;content-id=amzn1.sym.3343bdc6-9855-4dad-ae6a-60a908a293a7&amp;pf_rd_p=3343bdc6-9855-4dad-ae6a-60a908a293a7&amp;pf_rd_r=VS63VSQP0K5NV0A6YRR6&amp;pd_rd_wg=HwmZy&amp;pd_rd_r=4b6457c6-8bf6-450f-8277-303cd36a6a7e</value>
      <webElementGuid>4be2c152-4d81-4ab4-914b-04c60978b467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>f8ca809c-4799-4de3-a4b3-778c4277212c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>a-autoid-11-announce</value>
      <webElementGuid>d123b2a3-35c7-4bda-acac-bb82a76fb9c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-autoid-11&quot;)/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input&quot;]</value>
      <webElementGuid>4b227616-371f-4fd6-a1de-74a04d3cb254</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='submit.addToCart']</value>
      <webElementGuid>b2b5edef-d479-4110-a8cc-537abeb92921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='a-autoid-11']/span/input</value>
      <webElementGuid>fa7aa305-71b3-4fd5-b2d6-f3c2e76d32d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/span/span/input</value>
      <webElementGuid>edf2c7c1-5e96-4711-abb1-a9e4afcd4b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'submit.addToCart']</value>
      <webElementGuid>c309db39-8852-4db4-bdee-54dc0886cdaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
