<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_da vinci code</name>
   <tag></tag>
   <elementGuidId>eb528c19-6d24-4a2b-b71f-04a99583bbdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.s-suggestion.s-suggestion-ellipsis-direction</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-flyout-searchAjax']/div[2]/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c97f9030-d5bd-4da5-b8ca-e9f58b5ad347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>s-suggestion s-suggestion-ellipsis-direction</value>
      <webElementGuid>ea0e7e93-e6fd-4fda-aaa3-4e0332ff7627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f379aa52-7a69-431c-b09c-60cd669f87de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>da vinci code</value>
      <webElementGuid>cc0304df-1f28-4058-ad64-601e0c2f5b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>da vinci code</value>
      <webElementGuid>5a39bb99-a19f-4cea-a21f-a7ac53daef7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-flyout-searchAjax&quot;)/div[@class=&quot;autocomplete-results-container&quot;]/div[@class=&quot;two-pane-results-container&quot;]/div[@class=&quot;left-pane-results-container&quot;]/div[1]/div[@class=&quot;s-suggestion-container&quot;]/div[@class=&quot;s-suggestion s-suggestion-ellipsis-direction&quot;]</value>
      <webElementGuid>603cab29-6c45-4957-9caa-801dc1721ce8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-flyout-searchAjax']/div[2]/div/div/div/div/div</value>
      <webElementGuid>837a408b-a0a2-48d5-a206-df4ea13de523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/div</value>
      <webElementGuid>758b75af-e143-4c3d-a451-68364218718f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'da vinci code' or . = 'da vinci code')]</value>
      <webElementGuid>ae82729c-1c30-4b89-84ba-81c3d71ff1da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
