<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_s-image</name>
   <tag></tag>
   <elementGuidId>04a9225d-deda-458d-810a-dce7091ac667</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search']/div/div/div/span/div/div[2]/div/div/div/div/span/div/div/div/div/div/div[2]/div/span/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.s-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d06f7644-56fc-4828-a7cb-ede099340db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>s-image</value>
      <webElementGuid>401c776c-1ae6-43a3-a29e-bb99923631ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/617HlSnqzrL._AC_UY218_.jpg</value>
      <webElementGuid>b84dc76e-627e-47b7-8c1b-b7ac5d1de684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/617HlSnqzrL._AC_UY218_.jpg 1x, https://m.media-amazon.com/images/I/617HlSnqzrL._AC_UY327_FMwebp_QL65_.jpg 1.5x, https://m.media-amazon.com/images/I/617HlSnqzrL._AC_UY436_FMwebp_QL65_.jpg 2x, https://m.media-amazon.com/images/I/617HlSnqzrL._AC_UY545_FMwebp_QL65_.jpg 2.5x, https://m.media-amazon.com/images/I/617HlSnqzrL._AC_UY654_FMwebp_QL65_.jpg 3x</value>
      <webElementGuid>f10a1c2e-dd36-43b6-b246-e57ff0275ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sponsored Ad - Bmax Laptop 15.6&quot;, 16GB DDR4 RAM 512GB SSD, Intel Celeron N5095 Quad Core Processor (up to 2.9GHz), Windows...</value>
      <webElementGuid>27da0242-484e-43cc-aa15-4e0528168b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>918bc936-f1db-45df-bc27-93f33c2f973c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-latency</name>
      <type>Main</type>
      <value>s-product-image</value>
      <webElementGuid>9b81590f-dfb4-4fbb-b478-10c950d9b8d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-source-density</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a9fb002b-bbf2-433d-a7d2-4d6900ed321a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search&quot;)/div[@class=&quot;s-desktop-width-max s-desktop-content s-opposite-dir s-wide-grid-style sg-row&quot;]/div[@class=&quot;sg-col-20-of-24 s-matching-dir sg-col-16-of-20 sg-col sg-col-8-of-12 sg-col-12-of-16&quot;]/div[@class=&quot;sg-col-inner&quot;]/span[@class=&quot;rush-component s-latency-cf-section&quot;]/div[@class=&quot;s-main-slot s-result-list s-search-results sg-row&quot;]/div[@class=&quot;sg-col-20-of-24 s-result-item s-asin sg-col-0-of-12 sg-col-16-of-20 AdHolder sg-col s-widget-spacing-small sg-col-12-of-16&quot;]/div[@class=&quot;sg-col-inner&quot;]/div[@class=&quot;s-widget-container s-spacing-small s-widget-container-height-small celwidget slot=MAIN template=SEARCH_RESULTS widgetId=search-results_1&quot;]/div[@class=&quot;rush-component&quot;]/div[@class=&quot;rush-component s-featured-result-item&quot;]/span[@class=&quot;a-declarative&quot;]/div[@class=&quot;puis-card-container s-card-container s-overflow-hidden aok-relative puis-include-content-margin puis puis-v2rh3j15wdcp4q29xeaptoa72x6 s-latency-cf-section puis-card-border&quot;]/div[@class=&quot;a-section&quot;]/div[@class=&quot;puisg-row&quot;]/div[@class=&quot;puisg-col puisg-col-4-of-12 puisg-col-4-of-16 puisg-col-4-of-20 puisg-col-4-of-24 puis-list-col-left&quot;]/div[@class=&quot;puisg-col-inner&quot;]/div[@class=&quot;s-product-image-container aok-relative s-text-center s-image-overlay-grey puis-image-overlay-grey s-padding-left-small s-padding-right-small puis-flex-expand-height puis puis-v2rh3j15wdcp4q29xeaptoa72x6&quot;]/div[@class=&quot;aok-relative&quot;]/span[@class=&quot;rush-component&quot;]/a[@class=&quot;a-link-normal s-no-outline&quot;]/div[@class=&quot;a-section aok-relative s-image-fixed-height&quot;]/img[@class=&quot;s-image&quot;]</value>
      <webElementGuid>d66234bd-8307-4aec-afa7-5fcb707862e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search']/div/div/div/span/div/div[2]/div/div/div/div/span/div/div/div/div/div/div[2]/div/span/a/div/img</value>
      <webElementGuid>af597d60-c35d-4240-8823-a154aaf1184a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Sponsored Ad - Bmax Laptop 15.6&quot;, 16GB DDR4 RAM 512GB SSD, Intel Celeron N5095 Quad Core Processor (up to 2.9GHz), Windows...']</value>
      <webElementGuid>42a266d6-3b0f-4b18-9050-068af26ec2d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/img</value>
      <webElementGuid>e460cb9f-52dd-4614-acf4-57b009d3b417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://m.media-amazon.com/images/I/617HlSnqzrL._AC_UY218_.jpg' and @alt = 'Sponsored Ad - Bmax Laptop 15.6&quot;, 16GB DDR4 RAM 512GB SSD, Intel Celeron N5095 Quad Core Processor (up to 2.9GHz), Windows...']</value>
      <webElementGuid>9c54c128-e44d-4fc0-87a4-19eabf23b00d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
